### ISSUE TITLE
Demo eestec.portal on Deckart

### ISSUE THREAD

**Issue by zupo** [eestec/eestec.portal#28] opened 2012-12-02 16:57 UTC
Setup a Demo eestec.portal site on Deckart:
- nightly latest master code
- build environment
- add test content (will be done as part of #17)

This gives us:
- nice sandbox to play around and to showcase what the latest code does
- nice first point of contact for new developers
- nice "wow I did something" effect for developers as their code is online in tomorrow's Demo
- nice showcase for everyone else on what we are doing and how far along the way we are

**Comment by domenkozar** [comment] 2012-12-02 18:19
This is something I would like to work on. It's a duplicate of #16

**Comment by zupo** [comment] 2012-12-02 18:26
Not really a duplicate. Ticket #16 is about running latest production data with latest master code as staging to see if latest code works with latest data. Since data in there is still sensitive (as it's production data) we cannot give just anyone access to it.

Demo however, would have dummy, in-sensitive, data and we can freely distribute access to it to anyone as we rebuild the entire site every night.

**Comment by domenkozar** [comment] 2012-12-02 18:29
OK, that makes sense. Do we really need this? Seems like a "nice to have when we have extra time" :) Otherwise :+1:

**Comment by zupo** [comment] 2012-12-02 18:33
I'd have it sooner rather than later, do increase how much impact new developers can do. It's much easier to do than #16, especially one we have #17 done -- which we need to do soon anyhow.

**Comment by fakedrake** [comment] 2012-12-02 18:45
deckart is a server?

**Comment by balkian** [comment] 2012-12-02 19:13
Deckard is our new server :)

**Comment by balkian** [comment] 2013-04-08 20:37
http://demo.eestec.net/

**Closed as completed** 2013-04-08 20:37 UTC
